###### 128_5_real_quality_cross_tab_practice

,owner_department,site_name,site,monitoring_level,Buck-IC,NTF,はんだ,コイル,異物,total,check_level
0,品質保証2課,中国WSE,WSE,重点監視,3,1,0,1,3,8,異物重点確認
1,品質保証1課,メルモビ,MELMB,重点監視,1,1,1,5,0,8,コイル重点確認
2,品質保証1課,日本ISE,ISE,通常監視,0,1,2,1,3,7,異物重点確認
3,品質保証2課,中国GSE,GSE,通常監視,1,2,0,3,1,7,通常確認

###### practice questions 128_5_real_quality_cross_tab_practice.ipynb

In [2]:
import pandas as pd

In [3]:
df_defect = pd.DataFrame(
    [
        ["D001", "MELMB", "LCM-A", "J69P", "コイル", "RH Lo不灯", "2026-06-01"],
        ["D002", "MELMB", "LCM-A", "J69P", "コイル", "RH Hi/Lo不灯", "2026-06-02"],
        ["D003", "MELMB", "LCM-B", "J69P", "Buck-IC", "RH Lo不灯", "2026-06-03"],
        ["D004", "MELMB", "LCM-C", "310D", "NTF", "再現せず", "2026-06-03"],
        ["D005", "MELMB", "LCM-B", "310D", "はんだ", "点灯不安定", "2026-06-04"],
        ["D006", "MELMB", "LCM-A", "J69P", "コイル", "RH Lo不灯", "2026-06-05"],

        ["D007", "WSE", "LCM-A", "J69P", "コイル", "RH Lo不灯", "2026-06-01"],
        ["D008", "WSE", "LCM-B", "J69P", "Buck-IC", "全灯火不点灯", "2026-06-02"],
        ["D009", "WSE", "LCM-B", "J69P", "Buck-IC", "RH Lo不灯", "2026-06-03"],
        ["D010", "WSE", "LCM-C", "310D", "異物", "点灯不安定", "2026-06-04"],
        ["D011", "WSE", "LCM-C", "310D", "異物", "点灯不安定", "2026-06-05"],
        ["D012", "WSE", "LCM-D", "310D", "NTF", "再現せず", "2026-06-06"],

        ["D013", "GSE", "LCM-A", "J69P", "コイル", "RH Hi/Lo不灯", "2026-06-01"],
        ["D014", "GSE", "LCM-A", "J69P", "コイル", "RH Lo不灯", "2026-06-02"],
        ["D015", "GSE", "LCM-B", "J69P", "Buck-IC", "全灯火不点灯", "2026-06-03"],
        ["D016", "GSE", "LCM-C", "310D", "NTF", "再現せず", "2026-06-04"],
        ["D017", "GSE", "LCM-C", "310D", "NTF", "再現せず", "2026-06-05"],
        ["D018", "GSE", "LCM-D", "310D", "異物", "点灯不安定", "2026-06-06"],

        ["D019", "ISE", "LCM-A", "J69P", "コイル", "RH Lo不灯", "2026-06-01"],
        ["D020", "ISE", "LCM-B", "310D", "はんだ", "点灯不安定", "2026-06-02"],
        ["D021", "ISE", "LCM-B", "310D", "はんだ", "点灯不安定", "2026-06-03"],
        ["D022", "ISE", "LCM-C", "310D", "NTF", "再現せず", "2026-06-04"],
        ["D023", "ISE", "LCM-D", "310D", "異物", "点灯不安定", "2026-06-05"],
        ["D024", "ISE", "LCM-D", "310D", "異物", "点灯不安定", "2026-06-06"],

        ["D025", "MELMB", "LCM-A", "J69P", "コイル", "RH Lo不灯", "2026-06-07"],
        ["D026", "MELMB", "LCM-A", "J69P", "コイル", "RH Hi/Lo不灯", "2026-06-08"],
        ["D027", "WSE", "LCM-B", "J69P", "Buck-IC", "RH Lo不灯", "2026-06-08"],
        ["D028", "GSE", "LCM-A", "J69P", "コイル", "RH Lo不灯", "2026-06-09"],
        ["D029", "ISE", "LCM-D", "310D", "異物", "点灯不安定", "2026-06-09"],
        ["D030", "WSE", "LCM-C", "310D", "異物", "点灯不安定", "2026-06-10"],
    ],
    columns=[
        "defect_id",
        "site",
        "product",
        "project",
        "defect_category",
        "symptom",
        "occ_date",
    ],
)

In [5]:
df_defect.head()

  defect_id   site product project defect_category     symptom    occ_date
0      D001  MELMB   LCM-A    J69P             コイル     RH Lo不灯  2026-06-01
1      D002  MELMB   LCM-A    J69P             コイル  RH Hi/Lo不灯  2026-06-02
2      D003  MELMB   LCM-B    J69P         Buck-IC     RH Lo不灯  2026-06-03
3      D004  MELMB   LCM-C    310D             NTF        再現せず  2026-06-03
4      D005  MELMB   LCM-B    310D             はんだ       点灯不安定  2026-06-04

In [6]:
df_site_master = pd.DataFrame(
    [
        ["MELMB", "メルモビ", "品質保証1課", "重点監視"],
        ["WSE", "中国WSE", "品質保証2課", "重点監視"],
        ["GSE", "中国GSE", "品質保証2課", "通常監視"],
        ["ISE", "日本ISE", "品質保証1課", "通常監視"],
    ],
    columns=[
        "site",
        "site_name",
        "owner_department",
        "monitoring_level",
    ],
)
df_site_master

    site site_name owner_department monitoring_level
0  MELMB      メルモビ           品質保証1課             重点監視
1    WSE     中国WSE           品質保証2課             重点監視
2    GSE     中国GSE           品質保証2課             通常監視
3    ISE     日本ISE           品質保証1課             通常監視