In [11]:
import pandas as pd
df = pd.read_csv("service_detail_after_sample.csv")
df.head()

      レンタル開始日  顧客名  個数  期間 プラン  個数x期間    単価    契約金額 契約規模
0  2018/04/01  顧客A  15   1  通常     15  6000   90000   小口
1  2018/04/05  顧客B  15   2  学割     30  3500  105000   中口
2  2018/04/20  顧客C  10   2  通常     20  6000  120000   中口
3  2018/06/15  顧客A  20   2  通常     40  6000  240000   中口
4  2018/07/05  顧客B  15   2  学割     30  3500  105000   中口

In [12]:
grouped = df.groupby("顧客名")
grouped

In [13]:
df.groupby("顧客名").size()

顧客名
顧客A    3
顧客B    2
顧客C    2
顧客D    1
dtype: int64

In [14]:
summary_df = grouped["個数x期間"].agg(["size", "sum"])
summary_df

     size  sum
顧客名
顧客A     3  145
顧客B     2   60
顧客C     2   44
顧客D     1    8

In [15]:
summary_df = summary_df.rename(
    columns={
        "size": "契約回数",
        "sum": "個数x期間の合計"
    }
)
summary_df

     契約回数  個数x期間の合計
顧客名
顧客A     3       145
顧客B     2        60
顧客C     2        44
顧客D     1         8

In [16]:
summary_df["契約金額の合計"] = grouped["契約金額"].sum()
summary_df

     契約回数  個数x期間の合計  契約金額の合計
顧客名
顧客A     3       145   870000
顧客B     2        60   210000
顧客C     2        44   264000
顧客D     1         8    48000

In [18]:
bins = [-float("inf"), 100000, 600000, 1200000, 2400000, float("inf")]
summary_df["契約金額区分"] = pd.cut(
    summary_df["契約金額の合計"],
    bins
)
summary_df

     契約回数  個数x期間の合計  契約金額の合計                 契約金額区分
顧客名
顧客A     3       145   870000  (600000.0, 1200000.0]
顧客B     2        60   210000   (100000.0, 600000.0]
顧客C     2        44   264000   (100000.0, 600000.0]
顧客D     1         8    48000       (-inf, 100000.0]