In [4]:
import pandas as pd
#　データの読み込み
df = pd.read_table("dataset/review.tsv", encoding="shift_jis")
df.shape
# ---------------------------
# （1）表記揺れの修正
# ---------------------------
df["製品"] = df["製品"].str.upper()
df["製品"] = df["製品"].str.replace("-", "", regex=False)
df

        製品  レビュアー  評価
0    YQ310    655   4
1    PY110    115   5
2    PY220     26   2
3    PY220    760   3
4    YQ330    282   2
..     ...    ...  ..
295  PY310     97   2
296  YQ220    945   4
297  YQ110    675   4
298  PY220    442   5
299  PY330    363   4

[300 rows x 3 columns]

In [5]:
valid_names = {
    "PY110",
    "PY220",
    "PY310",
    "PY330",
    "YQ110",
    "YQ220",
    "YQ310",
    "YQ330",
}

In [6]:
invalid_df = df[~df["製品"].isin(valid_names)]

In [7]:
df["シリーズ名"] = df["製品"].str[:2]

In [8]:
df["バージョン番号"] = df["製品"].str[2:]

In [9]:
df.head()

      製品  レビュアー  評価 シリーズ名 バージョン番号
0  YQ310    655   4    YQ     310
1  PY110    115   5    PY     110
2  PY220     26   2    PY     220
3  PY220    760   3    PY     220
4  YQ330    282   2    YQ     330