In [5]:
import pandas as pd
df = pd.read_csv("event_after_sample.csv")
df.head()

,イベント日,勉強会グループ,イベント,開催形式,定員,登録者数,リモート可,参加者数,満席率,カテゴリー
0,2019-01-23,Python輪読会,Python輪読会 No.1,S,20,19,False,19,0.95,輪読
1,2019-01-26,初心者の会,もくもく自習会,SL,20,12,True,12,0.60,自習
2,2019-01-27,なまこ部,Talk#1,SL,20,12,True,12,0.60,一般
3,2019-01-30,Python輪読会,Python輪読会 No.2,S,20,15,False,15,0.75,輪読
4,2019-02-02,電子工作シリーズ,CO2測定,S,50,55,False,50,1.10,一般

In [6]:
grouped = df.groupby("勉強会グループ")
summary_df = grouped["リモート可"].agg(["size", "sum"])
summary_df = summary_df.rename(
    columns={
        "size": "イベント数",
        "sum": "リモート可のイベント数"
    }
)
summary_df["参加者の延べ人数"] = grouped["参加者数"].sum()

bins = [-float("inf"), 50, 100, 500, 1000, float("inf")]
summary_df["参加者の延べ人数の区分"] = pd.cut(
    summary_df["参加者の延べ人数"],
    bins,
    right=False
)
summary_df

           イベント数  リモート可のイベント数  参加者の延べ人数    参加者の延べ人数の区分
勉強会グループ
Python輪読会      3            0        54  [50.0, 100.0)
なまこ部           3            3        50  [50.0, 100.0)
初心者の会          3            3        65  [50.0, 100.0)
電子工作シリーズ       1            0        50  [50.0, 100.0)