###### 130_2_site_defect_category_list_practice.ipynb

In [1]:
#cell1
import pandas as pd
pd.set_option("display.max_columns", None)

In [2]:
#cell2
df_site = pd.DataFrame(
    [
        ["SUS", "North America", "北米拠点"],
        ["WSE", "China", "中国拠点"],
        ["GSE", "China", "中国拠点"],
        ["MELMB", "China", "中国拠点"],
        ["ISE", "Japan", "日本拠点"],
    ],
    columns=[
        "site",
        "area",
        "site_group",
    ],
)
df_site

    site           area site_group
0    SUS  North America       北米拠点
1    WSE          China       中国拠点
2    GSE          China       中国拠点
3  MELMB          China       中国拠点
4    ISE          Japan       日本拠点

In [3]:
df_defect = pd.DataFrame(
    [
        ["SUS", "J69P", "コイル", 3],
        ["SUS", "J69P", "Buck-IC", 1],
        ["SUS", "J69P", "コイル", 2],
        ["SUS", "310D", "NTF", 1],
        ["WSE", "310D", "コイル", 2],
        ["WSE", "310D", "NTF", 0],
        ["GSE", "J69P", "コイル", 4],
        ["GSE", "J69P", "Buck-IC", 2],
        ["MELMB", "310D", "コイル", 5],
        ["MELMB", "310D", "NTF", 1],
    ],
    columns=[
        "site",
        "model",
        "defect_category",
        "defect_qty",
    ],
)

df_defect

    site model defect_category  defect_qty
0    SUS  J69P             コイル           3
1    SUS  J69P         Buck-IC           1
2    SUS  J69P             コイル           2
3    SUS  310D             NTF           1
4    WSE  310D             コイル           2
5    WSE  310D             NTF           0
6    GSE  J69P             コイル           4
7    GSE  J69P         Buck-IC           2
8  MELMB  310D             コイル           5
9  MELMB  310D             NTF           1

In [7]:
#cell4

df_category = (
    df_defect.groupby(
        "site",
        as_index=False,
    )["defect_category"]
    .agg(lambda x: "/".join(x.drop_duplicates()))
    .rename(
        columns={
            "defect_category": "defect_category_list",
        }
    )
)

df_category

    site defect_category_list
0    GSE          コイル/Buck-IC
1  MELMB              コイル/NTF
2    SUS      コイル/Buck-IC/NTF
3    WSE              コイル/NTF

In [8]:
#cell5 
df_result = pd.merge(
    df_site,
    df_category,
    on="site",
    how="left",
)
df_result

    site           area site_group defect_category_list
0    SUS  North America       北米拠点      コイル/Buck-IC/NTF
1    WSE          China       中国拠点              コイル/NTF
2    GSE          China       中国拠点          コイル/Buck-IC
3  MELMB          China       中国拠点              コイル/NTF
4    ISE          Japan       日本拠点                  NaN

In [9]:
#cell6
df_result["defect_category_list"] = (
    df_result["defect_category_list"].fillna("発生無し")
)
df_result

    site           area site_group defect_category_list
0    SUS  North America       北米拠点      コイル/Buck-IC/NTF
1    WSE          China       中国拠点              コイル/NTF
2    GSE          China       中国拠点          コイル/Buck-IC
3  MELMB          China       中国拠点              コイル/NTF
4    ISE          Japan       日本拠点                 発生無し

In [10]:
#cell4-1
df_category_base = df_defect[
    [
        "site",
        "defect_category",
    ]
].copy()
df_category_base

    site defect_category
0    SUS             コイル
1    SUS         Buck-IC
2    SUS             コイル
3    SUS             NTF
4    WSE             コイル
5    WSE             NTF
6    GSE             コイル
7    GSE         Buck-IC
8  MELMB             コイル
9  MELMB             NTF

In [11]:
#cell 4-2
df_category_unique = df_category_base.drop_duplicates()
df_category_unique

    site defect_category
0    SUS             コイル
1    SUS         Buck-IC
3    SUS             NTF
4    WSE             コイル
5    WSE             NTF
6    GSE             コイル
7    GSE         Buck-IC
8  MELMB             コイル
9  MELMB             NTF

In [ ]:
#4-3
df_category = (
    df_category_unique.groupby(
        "site",
        as_index=False,
    )["defect_category"].agg("/".join)
)
df_category

    site  defect_category
0    GSE      コイル/Buck-IC
1  MELMB          コイル/NTF
2    SUS  コイル/Buck-IC/NTF
3    WSE          コイル/NTF

In [ ]:
#4-4
df_category =df_category.rename(
    columns={
        "defect_category": "defect_category_list",
    }
)
df_category

    site defect_category_list
0    GSE          コイル/Buck-IC
1  MELMB              コイル/NTF
2    SUS      コイル/Buck-IC/NTF
3    WSE              コイル/NTF