In [2]:
import pandas as pd

In [5]:
df_quality = pd.DataFrame(
    [
         ["2026-06", "MELMB", "Lamp-A", "不点灯", 18, "対応中"],
        ["2026-06", "WSE", "Lamp-B", "ちらつき", 32, "未対応"],
        ["2026-06", "GSE", "Lamp-C", "外観不良", 9, "完了"],
        ["2026-07", "MELMB", "Lamp-A", "不点灯", 25, "対応中"],
        ["2026-07", "WSE", "Lamp-B", "ショート", 45, "未対応"],
        ["2026-07", "GSE", "Lamp-C", "外観不良", 7, "完了"],
    ],
    columns=[
        "month",
        "site",
        "product",
        "defect_type",
        "defect_qty",
        "status",
    ],
)
df_quality

     month   site product defect_type  defect_qty status
0  2026-06  MELMB  Lamp-A         不点灯          18    対応中
1  2026-06    WSE  Lamp-B        ちらつき          32    未対応
2  2026-06    GSE  Lamp-C        外観不良           9     完了
3  2026-07  MELMB  Lamp-A         不点灯          25    対応中
4  2026-07    WSE  Lamp-B        ショート          45    未対応
5  2026-07    GSE  Lamp-C        外観不良           7     完了

In [7]:
df_site = df_quality[["site"]]
df_site

    site
0  MELMB
1    WSE
2    GSE
3  MELMB
4    WSE
5    GSE