###### 131_1_replace_number_in_comment_answer.ipynb

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("dataset/review.csv", index_col="user_id")
df

         rating                                           comment
user_id
U101          5  Py-220を購入。他社と比べると1000円ほど高いですが、その分値段に見合う品質だと思います。
U102          3                2月の寒い時期に買ったけど3か月で壊れた（使用頻度は1日5回くらい）
U103          3          前回PY-110を買って、リピでPY-210を買いました。タイマー機能が便利です
U104          4   Pyシリーズはずっと使ってるのですが、使わない時に折りたためるのが○ですね。あとヘビが可愛い。
U105          5          カラーが選べるので220にしました。目立ちすぎず部屋に馴染むので気に入っています

In [3]:
df["comment"] = df["comment"].str.replace(r"\d+", "#", regex=True)
df

         rating                                          comment
user_id
U101          5      Py-#を購入。他社と比べると#円ほど高いですが、その分値段に見合う品質だと思います。
U102          3               #月の寒い時期に買ったけど#か月で壊れた（使用頻度は#日#回くらい）
U103          3             前回PY-#を買って、リピでPY-#を買いました。タイマー機能が便利です
U104          4  Pyシリーズはずっと使ってるのですが、使わない時に折りたためるのが○ですね。あとヘビが可愛い。
U105          5           カラーが選べるので#にしました。目立ちすぎず部屋に馴染むので気に入っています