In [1]:
import pandas as pd

df_log = pd.read_csv("dataset/product_log.csv")
df_master = pd.read_csv("dataset/product_master.csv")

In [2]:
df_log.count()

Date       40
Num        36
Product    40
dtype: int64

In [3]:
df_log[df_log.isnull().any(axis=1)]

          Date  Num Product
16  2017-02-08  NaN       A
19  2017-02-16  NaN       A
20  2017-02-18  NaN       A
23  2017-02-24  NaN       A

In [4]:
df_log["Num"] = df_log["Num"].interpolate()

In [5]:
df_log.count()

Date       40
Num        40
Product    40
dtype: int64

In [7]:
df_log["Num"].isnull().sum()

np.int64(0)

In [8]:
df_log[df_log.isnull().any(axis=1)]

Empty DataFrame
Columns: [Date, Num, Product]
Index: []

In [9]:
df_log["Num"] = df_log["Num"].interpolate()

In [10]:
#練習1
#Num 列を補間したあと、df_log.isnull().sum() で各列の欠損数を確認してください。
df_log["Num"] = df_log["Num"].interpolate()
df_log.isnull().sum()

Date       0
Num        0
Product    0
dtype: int64

In [11]:
#練習2
#Num 列を補間せずに、平均値で埋めるコードを書いてください。
df_log["Num"] = df_log["Num"].fillna(df_log["Num"].mean())

In [12]:
df_log["Num"] = df_log["Num"].fillna(0)