In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame([[0], [1]], columns=["A"])
df

   A
0  0
1  1

In [4]:
import pandas as pd

df = pd.DataFrame([[1], [0]], columns=["A"])
df

   A
0  1
1  0

In [5]:
df = pd.DataFrame([[0], [1]], columns=["B"])
df

   B
0  0
1  1

In [9]:
import pandas as pd

data = [[0], [1], [0]]
col_names = ["A"]
df = pd.DataFrame(data, columns=col_names)
df

   A
0  0
1  1
2  0

In [10]:
import pandas as pd

df = pd.DataFrame([[0], [1], [0]], columns=["A"])
df

   A
0  0
1  1
2  0

In [11]:
import pandas as pd

df = pd.DataFrame([[0], [1]], columns=["X"])
df

   X
0  0
1  1

In [12]:
import pandas as pd
df = pd.DataFrame([[0], [1]], columns=["Test"])
df

   Test
0     0
1     1