###### 132_5_pyq_week_group_answer.ipynb

In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("dataset/study_log_2months.csv",
                 parse_dates=["start_at", "end_at"]
)
df

,id,user_name,subject,start_at,end_at
0,1,Alice,数学,2021-12-01 20:06:06.483196+09:00,2021-12-01 21:31:50.743590+09:00
1,2,Bob,英語,2021-12-01 22:49:20.341135+09:00,2021-12-01 23:59:20.661257+09:00
2,3,Bob,英語,2021-12-02 00:12:08.341451+09:00,2021-12-01 00:45:34.854274+09:00
3,4,Alice,情報,2021-12-02 20:15:18.171897+09:00,2021-12-02 21:46:49.722756+09:00
4,5,Alice,理科,2021-12-03 21:32:22.590773+09:00,2021-12-03 22:20:02.185758+09:00
...,...,...,...,...,...
143,144,Alice,数学,2022-01-30 11:30:51.281316+09:00,2022-01-30 11:55:03.915218+09:00
144,145,Alice,数学,2022-01-30 13:30:36.071372+09:00,2022-01-30 13:55:45.799818+09:00
145,146,Alice,理科,2022-01-30 14:20:17.776030+09:00,2022-01-30 16:51:29.587649+09:00
146,147,Alice,英語,2022-01-31 06:12:05.683368+09:00,2021-01-31 07:01:44.368948+09:00
147,148,Alice,社会,2022-01-31 20:12:40.352115+09:00,2021-01-31 21:58:12.285765+09:00

In [4]:
df.head(1)

,id,user_name,subject,start_at,end_at
0,1,Alice,数学,2021-12-01 20:06:06.483196+09:00,2021-12-01 21:31:50.743590+09:00

In [5]:
iso_df = df["start_at"].dt.isocalendar()

In [6]:
iso_df

     year  week  day
0    2021    48    3
1    2021    48    3
2    2021    48    4
3    2021    48    4
4    2021    48    5
..    ...   ...  ...
143  2022     4    7
144  2022     4    7
145  2022     4    7
146  2022     5    1
147  2022     5    1

[148 rows x 3 columns]

In [8]:
iso_df.head()

   year  week  day
0  2021    48    3
1  2021    48    3
2  2021    48    4
3  2021    48    4
4  2021    48    5

In [9]:
df["week_group"] = iso_df["year"] * 100 + iso_df["week"]

In [10]:
df["week_group"]

0      202148
1      202148
2      202148
3      202148
4      202148
        ...
143    202204
144    202204
145    202204
146    202205
147    202205
Name: week_group, Length: 148, dtype: UInt32

In [11]:
df[
    (df["start_at"] >= "2021-12-27")
    & (df["start_at"] < "2022-01-10")
][
    [
        "id",
        "user_name",
        "subject",
        "start_at",
        "week_group",
    ]
]

    id user_name subject                         start_at  week_group
60  61      Dave      社会 2021-12-27 04:26:01.654859+09:00      202152
61  62      Dave      英語 2021-12-27 10:48:30.955329+09:00      202152
62  63       Bob      理科 2021-12-27 21:49:43.567852+09:00      202152
63  64       Bob      社会 2021-12-28 03:58:01.172253+09:00      202152
64  65     Carol      数学 2021-12-28 20:41:53.347873+09:00      202152
65  66       Bob      英語 2021-12-29 01:40:31.372618+09:00      202152
66  67     Alice      情報 2021-12-29 18:08:44.742874+09:00      202152
67  68      Dave      理科 2021-12-29 22:33:37.591819+09:00      202152
68  69     Carol      情報 2021-12-30 06:38:48.479568+09:00      202152
69  70     Alice      英語 2021-12-31 00:29:36.697104+09:00      202152
70  71      Dave      理科 2021-12-31 08:03:47.730132+09:00      202152
71  72     Alice      社会 2021-12-31 18:54:39.573173+09:00      202152
72  73     Alice      数学 2022-01-01 04:12:13.612858+09:00      202152
73  74     Carol      英語 2022-01-01 16:18:56.547744+09:00      202152
74  75     Carol      情報 2022-01-01 18:26:32.918803+09:00      202152
75  76       Bob      数学 2022-01-02 11:44:55.523346+09:00      202152
76  77     Alice      英語 2022-01-02 16:37:37.176968+09:00      202152
77  78       Bob      数学 2022-01-02 23:59:05.263190+09:00      202152
78  79     Carol      理科 2022-01-03 16:50:50.681643+09:00      202201
79  80       Bob      理科 2022-01-04 02:20:37.759081+09:00      202201
80  81      Dave      社会 2022-01-04 13:11:39.130147+09:00      202201
81  82       Bob      数学 2022-01-04 19:27:53.149988+09:00      202201
82  83      Dave      情報 2022-01-05 07:57:53.201920+09:00      202201
83  84       Bob      数学 2022-01-05 18:18:16.630665+09:00      202201
84  85       Bob      数学 2022-01-05 22:05:42.528651+09:00      202201
85  86     Carol      理科 2022-01-06 08:35:56.239965+09:00      202201
86  87       Bob      理科 2022-01-06 23:05:12.979454+09:00      202201
87  88      Dave      情報 2022-01-07 01:18:25.103623+09:00      202201
88  89      Dave      情報 2022-01-07 15:23:47.475445+09:00      202201
89  90       Bob      数学 2022-01-08 02:22:58.688399+09:00      202201
90  91       Bob      数学 2022-01-08 09:06:48.429760+09:00      202201
91  92      Dave      情報 2022-01-08 21:42:07.617675+09:00      202201
92  93     Alice      英語 2022-01-09 09:26:00.412376+09:00      202201
93  94       Bob      英語 2022-01-09 17:28:52.621424+09:00      202201
94  95     Alice      情報 2022-01-09 20:02:07.558719+09:00      202201