###### 126-2: 最小と最大を抽出するには

In [10]:
import numpy as np
import pandas as pd

df = pd.DataFrame(
    [
        ["Alice", "", 87],
        ["Alice", "", np.nan],
        ["Bob", "", 65],
        ["Bob", "", 92],
    ],
    columns= ["Name", "Subject", "Point"],
)
print(df.Point.min())
print(df.Point.max())
df.Point == df.Point.min()
df.Point == df.Point.max()
#df[(df.Point == df.Point.min()) | (df.Point == df.Point.max())]

65.0
92.0

0    False
1    False
2    False
3     True
Name: Point, dtype: bool

In [15]:
import pandas as pd

df_quality = pd.DataFrame(
    [
        ["melmb", "a001", 1200.0],
        ["wse", "a002", 850.0],
        ["gse", "a003", 2300.0],
        ["ise", "a004", 400.0],
    ],
    columns=["site", "product", "ppm"],
)

df_quality[
    (df_quality["ppm"] == df_quality["ppm"].min()) |
    (df_quality["ppm"] == df_quality["ppm"].max())
]

  site product     ppm
2  gse    a003  2300.0
3  ise    a004   400.0

In [17]:
import pandas as pd

df_defect = pd.DataFrame(
    [
        ["melmb", "lamp-a", 12],
        ["wse", "lamp-b", 5],
        ["gse", "lamp-c", 28],
        ["ise", "lamp-d", 5],
    ],
    columns=["site", "product", "defects"]
)
df_defect[
    (df_defect["defects"] == df_defect["defects"].min()) |
    (df_defect["defects"] == df_defect["defects"].max())
]

  site product  defects
1  wse  lamp-b        5
2  gse  lamp-c       28
3  ise  lamp-d        5

###### 実務問題２

In [1]:
import pandas as pd
import numpy as np

df_report = pd.DataFrame(
    [
         ["2026-06-01", "MELMB", "Lamp-A", "点灯不良", 12000, 18],
        ["2026-06-01", "WSE", "Lamp-B", "外観キズ", 9000, 3],
        ["2026-06-02", "GSE", "Lamp-C", "寸法NG", 10000, 24],
        ["2026-06-02", "ISE", "Lamp-D", "異物混入", 8000, 2],
        ["2026-06-03", "MEAX", "Lamp-E", "点灯不良", 7000, 16],
        ["2026-06-03", "MELAC", "Lamp-F", "はんだ不良", 6000, np.nan],
    ],
    columns=["date", "site", "product", "defect_type", "production", "defects"],
)

df_report["ppm"] = df_report["defects"] / df_report["production"] * 1000000
df_report["ppm"] = df_report["ppm"].round(1)

In [2]:
df_ppm_min_max = df_report[
    (df_report["ppm"] == df_report["ppm"].min()) |
    (df_report["ppm"] == df_report["ppm"].max())
]

In [4]:
df_ppm_min_max_sorted = df_ppm_min_max.sort_values(by="ppm", ascending=False)
print(df_ppm_min_max_sorted)

         date site product defect_type  production  defects     ppm
2  2026-06-02  GSE  Lamp-C        寸法NG       10000     24.0  2400.0
3  2026-06-02  ISE  Lamp-D        異物混入        8000      2.0   250.0