###### 131_6_get_dummies_basic_answer.ipynb

In [1]:
import pandas as pd

In [3]:
df = pd.read_table("dataset/enquete.tsv")
df

  user_id deciding_factor
0    S001           価格,機能
1    S002     価格,デザイン,その他
2    S003          機能,安全性
3    S004             その他
4    S005      価格,デザイン,機能

In [8]:
dummied_df = df["deciding_factor"].str.get_dummies(sep=",")
dummied_df

   その他  デザイン  価格  安全性  機能
0    0     0   1    0   1
1    1     1   1    0   0
2    0     0   0    1   1
3    1     0   0    0   0
4    0     1   1    0   1

In [9]:
df = df.join(dummied_df)

In [10]:
df

  user_id deciding_factor  その他  デザイン  価格  安全性  機能
0    S001           価格,機能    0     0   1    0   1
1    S002     価格,デザイン,その他    1     1   1    0   0
2    S003          機能,安全性    0     0   0    1   1
3    S004             その他    1     0   0    0   0
4    S005      価格,デザイン,機能    0     1   1    0   1