###### 132_8_weekly_resample_answer.ipynb

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(
    "dataset/study_total_minutes_1month.csv",
    parse_dates=["date"],
    index_col="date",
)
df

            total_minutes
date
2021-12-30             45
2021-12-31             21
2022-01-01             32
2022-01-03            156
2022-01-05            201
2022-01-06             34
2022-01-09            542
2022-01-10            360
2022-01-11            123
2022-01-15             21
2022-01-19            220
2022-01-24             32
2022-01-25            110
2022-01-29            347

In [3]:
agg_df = df.resample("W").agg(
    ["min", "max", "mean", "sum", "count"]
)

In [4]:
agg_df

           total_minutes
                     min  max        mean  sum count
date
2022-01-02            21   45   32.666667   98     3
2022-01-09            34  542  233.250000  933     4
2022-01-16            21  360  168.000000  504     3
2022-01-23           220  220  220.000000  220     1
2022-01-30            32  347  163.000000  489     3