###### 131_3_exclude_specific_string_answer.ipynb

In [4]:
import pandas as pd

In [6]:
df = pd.read_csv("dataset/review.csv", index_col="user_id")
df

         rating                                           comment
user_id
U101          5  Py-220を購入。他社と比べると1000円ほど高いですが、その分値段に見合う品質だと思います。
U102          3                2月の寒い時期に買ったけど3か月で壊れた（使用頻度は1日5回くらい）
U103          3          前回PY-110を買って、リピでPY-210を買いました。タイマー機能が便利です
U104          4   Pyシリーズはずっと使ってるのですが、使わない時に折りたためるのが○ですね。あとヘビが可愛い。
U105          5          カラーが選べるので220にしました。目立ちすぎず部屋に馴染むので気に入っています

In [7]:
contains_py = df["comment"].str.contains(
    "PY",
    case=False,
)
contains_py

user_id
U101     True
U102    False
U103     True
U104     True
U105    False
Name: comment, dtype: bool

In [8]:
not_contains_py = ~contains_py
not_contains_py

user_id
U101    False
U102     True
U103    False
U104    False
U105     True
Name: comment, dtype: bool

In [9]:
selected_df = df[not_contains_py].copy()
selected_df

         rating                                   comment
user_id
U102          3        2月の寒い時期に買ったけど3か月で壊れた（使用頻度は1日5回くらい）
U105          5  カラーが選べるので220にしました。目立ちすぎず部屋に馴染むので気に入っています