###### 128_6_split_to_cross_tab_practice

###### 128_6_lcm_split_to_cross_tab.ipynb

In [2]:
import pandas as pd

In [3]:
df_ticket = pd.DataFrame(
    [
        ["T001", "J69P", "MELMB/Line1/組立", "コイル/鉄粉/ショート", "RH Lo不灯", 2],
        ["T002", "J69P", "MELMB/Line1/検査", "コイル/巻線ばらつき", "RH Hi/Lo不灯", 3],
        ["T003", "J69P", "MELMB/Line2/組立", "Buck-IC/焼損", "全灯火不点灯", 5],
        ["T004", "310D", "WSE/Line1/検査", "異物/混入", "点灯不安定", 1],
        ["T005", "310D", "WSE/Line2/組立", "はんだ/クラック", "点灯不安定", 4],
        ["T006", "J69P", "GSE/Line1/組立", "コイル/鉄粉/ショート", "RH Lo不灯", 2],
        ["T007", "310D", "GSE/Line2/検査", "NTF", "再現せず", 1],
        ["T008", "J69P", "ISE/Line1/組立", "コイル/巻線ばらつき", "RH Lo不灯", 3],
        ["T009", "310D", "ISE/Line1/検査", "異物/付着", "点灯不安定", 2],
        ["T010", "J69P", "WSE/Line2/検査", "Buck-IC/焼損", "RH Lo不灯", 4],
        ["T011", "310D", "MELMB/Line2/組立", "はんだ/濡れ不足", "点灯不安定", 3],
        ["T012", "J69P", "GSE/Line1/検査", "コイル/鉄粉/ショート", "RH Hi/Lo不灯", 5],
    ],
    columns=[
        "ticket_id",
        "project",
        "発生場所",
        "原因タグ",
        "symptom",
        "risk_score",
    ],
)
df_ticket.head(3)

  ticket_id project            発生場所         原因タグ     symptom  risk_score
0      T001    J69P  MELMB/Line1/組立  コイル/鉄粉/ショート     RH Lo不灯           2
1      T002    J69P  MELMB/Line1/検査   コイル/巻線ばらつき  RH Hi/Lo不灯           3
2      T003    J69P  MELMB/Line2/組立   Buck-IC/焼損      全灯火不点灯           5

In [4]:
df_site_master = pd.DataFrame(
    [
         ["MELMB", "メルモビ", "品質保証1課", "重点監視"],
        ["WSE", "中国WSE", "品質保証2課", "重点監視"],
        ["GSE", "中国GSE", "品質保証2課", "通常監視"],
        ["ISE", "日本ISE", "品質保証1課", "通常監視"],
    ],
    columns=[
        "拠点",
        "拠点名",
        "担当部署",
        "監視区分",
    ],
)
df_site_master

      拠点    拠点名    担当部署  監視区分
0  MELMB   メルモビ  品質保証1課  重点監視
1    WSE  中国WSE  品質保証2課  重点監視
2    GSE  中国GSE  品質保証2課  通常監視
3    ISE  日本ISE  品質保証1課  通常監視

In [5]:
df_ticket[["拠点", "ライン", "工程"]] = df_ticket["発生場所"].str.split("/", expand=True)
df_ticket.head(3)

,ticket_id,project,発生場所,原因タグ,symptom,risk_score,拠点,ライン,工程
0,T001,J69P,MELMB/Line1/組立,コイル/鉄粉/ショート,RH Lo不灯,2,MELMB,Line1,組立
1,T002,J69P,MELMB/Line1/検査,コイル/巻線ばらつき,RH Hi/Lo不灯,3,MELMB,Line1,検査
2,T003,J69P,MELMB/Line2/組立,Buck-IC/焼損,全灯火不点灯,5,MELMB,Line2,組立

In [6]:
df_ticket[["原因1", "原因2", "原因3"]] = df_ticket["原因タグ"].str.split("/", expand=True)
df_ticket.head(3)

,ticket_id,project,発生場所,原因タグ,symptom,risk_score,拠点,ライン,工程,原因1,原因2,原因3
0,T001,J69P,MELMB/Line1/組立,コイル/鉄粉/ショート,RH Lo不灯,2,MELMB,Line1,組立,コイル,鉄粉,ショート
1,T002,J69P,MELMB/Line1/検査,コイル/巻線ばらつき,RH Hi/Lo不灯,3,MELMB,Line1,検査,コイル,巻線ばらつき,None
2,T003,J69P,MELMB/Line2/組立,Buck-IC/焼損,全灯火不点灯,5,MELMB,Line2,組立,Buck-IC,焼損,None

In [7]:
df_ticket[["原因1","原因2", "原因3"]] = df_ticket[["原因1","原因2", "原因3"]].fillna("")
df_ticket

,ticket_id,project,発生場所,原因タグ,symptom,risk_score,拠点,ライン,工程,原因1,原因2,原因3
0,T001,J69P,MELMB/Line1/組立,コイル/鉄粉/ショート,RH Lo不灯,2,MELMB,Line1,組立,コイル,鉄粉,ショート
1,T002,J69P,MELMB/Line1/検査,コイル/巻線ばらつき,RH Hi/Lo不灯,3,MELMB,Line1,検査,コイル,巻線ばらつき,
2,T003,J69P,MELMB/Line2/組立,Buck-IC/焼損,全灯火不点灯,5,MELMB,Line2,組立,Buck-IC,焼損,
3,T004,310D,WSE/Line1/検査,異物/混入,点灯不安定,1,WSE,Line1,検査,異物,混入,
4,T005,310D,WSE/Line2/組立,はんだ/クラック,点灯不安定,4,WSE,Line2,組立,はんだ,クラック,
5,T006,J69P,GSE/Line1/組立,コイル/鉄粉/ショート,RH Lo不灯,2,GSE,Line1,組立,コイル,鉄粉,ショート
6,T007,310D,GSE/Line2/検査,NTF,再現せず,1,GSE,Line2,検査,NTF,,
7,T008,J69P,ISE/Line1/組立,コイル/巻線ばらつき,RH Lo不灯,3,ISE,Line1,組立,コイル,巻線ばらつき,
8,T009,310D,ISE/Line1/検査,異物/付着,点灯不安定,2,ISE,Line1,検査,異物,付着,
9,T010,J69P,WSE/Line2/検査,Buck-IC/焼損,RH Lo不灯,4,WSE,Line2,検査,Buck-IC,焼損,
10,T011,310D,MELMB/Line2/組立,はんだ/濡れ不足,点灯不安定,3,MELMB,Line2,組立,はんだ,濡れ不足,
11,T012,J69P,GSE/Line1/検査,コイル/鉄粉/ショート,RH Hi/Lo不灯,5,GSE,Line1,検査,コイル,鉄粉,ショート

In [8]:
df_cross = df_ticket.pivot_table(
    values="ticket_id",
    index="拠点",
    columns="原因1",
    aggfunc="count",
    fill_value=0,
)
df_cross

原因1    Buck-IC  NTF  はんだ  コイル  異物
拠点
GSE          0    1    0    2   0
ISE          0    0    0    1   1
MELMB        1    0    1    2   0
WSE          1    0    1    0   1

In [9]:
df_cross = df_cross[
    [
        "Buck-IC",
        "NTF",
        "はんだ",
        "コイル",
        "異物"
    ]
].copy()

In [10]:
df_cross["total"] = df_cross.sum(axis=1)
df_cross

原因1    Buck-IC  NTF  はんだ  コイル  異物  total
拠点
GSE          0    1    0    2   0      3
ISE          0    0    0    1   1      2
MELMB        1    0    1    2   0      4
WSE          1    0    1    0   1      3

In [11]:
df_cross_sort = df_cross.sort_values(
    "total",
    ascending=False,
)
df_cross_sort

原因1    Buck-IC  NTF  はんだ  コイル  異物  total
拠点
MELMB        1    0    1    2   0      4
GSE          0    1    0    2   0      3
WSE          1    0    1    0   1      3
ISE          0    0    0    1   1      2

In [12]:
df_cross_sort = df_cross_sort.reset_index()
df_cross_sort

原因1     拠点  Buck-IC  NTF  はんだ  コイル  異物  total
0    MELMB        1    0    1    2   0      4
1      GSE        0    1    0    2   0      3
2      WSE        1    0    1    0   1      3
3      ISE        0    0    0    1   1      2

In [13]:
df_report = df_cross_sort.merge(
    df_site_master,
    on="拠点"
)
df_report

      拠点  Buck-IC  NTF  はんだ  コイル  異物  total    拠点名    担当部署  監視区分
0  MELMB        1    0    1    2   0      4   メルモビ  品質保証1課  重点監視
1    GSE        0    1    0    2   0      3  中国GSE  品質保証2課  通常監視
2    WSE        1    0    1    0   1      3  中国WSE  品質保証2課  重点監視
3    ISE        0    0    0    1   1      2  日本ISE  品質保証1課  通常監視

In [14]:
df_report = df_report[
    [
        "担当部署",
        "拠点名",
        "拠点",
        "監視区分",
        "Buck-IC",
        "NTF",
        "はんだ",
        "コイル",
        "異物",
        "total",
    ]
].copy()
df_report.head(3)

     担当部署    拠点名     拠点  監視区分  Buck-IC  NTF  はんだ  コイル  異物  total
0  品質保証1課   メルモビ  MELMB  重点監視        1    0    1    2   0      4
1  品質保証2課  中国GSE    GSE  通常監視        0    1    0    2   0      3
2  品質保証2課  中国WSE    WSE  重点監視        1    0    1    0   1      3

In [17]:
df_report["check_level"] = "通常確認"
#df_report.head(1)

df_report.loc[
    df_report["total"] >= 4,
    "check_level",
] = "全体件数重点確認"
#df_report

df_report.loc[
    df_report["コイル"] >= 2,
    "check_level",
] = "コイル重点確認"
df_report

df_report.loc[
    df_report["Buck-IC"] >= 1,
    "check_level",
] = "Buck-IC確認"
df_report

     担当部署    拠点名     拠点  監視区分  Buck-IC  NTF  はんだ  コイル  異物  total check_level
0  品質保証1課   メルモビ  MELMB  重点監視        1    0    1    2   0      4   Buck-IC確認
1  品質保証2課  中国GSE    GSE  通常監視        0    1    0    2   0      3     コイル重点確認
2  品質保証2課  中国WSE    WSE  重点監視        1    0    1    0   1      3   Buck-IC確認
3  品質保証1課  日本ISE    ISE  通常監視        0    0    0    1   1      2        通常確認

In [18]:
df_priority = df_report[
    df_report["check_level"] != "通常確認"
].copy()

df_priority

     担当部署    拠点名     拠点  監視区分  Buck-IC  NTF  はんだ  コイル  異物  total check_level
0  品質保証1課   メルモビ  MELMB  重点監視        1    0    1    2   0      4   Buck-IC確認
1  品質保証2課  中国GSE    GSE  通常監視        0    1    0    2   0      3     コイル重点確認
2  品質保証2課  中国WSE    WSE  重点監視        1    0    1    0   1      3   Buck-IC確認