###### 130_1_site_total_defect_transform_practice.ipynb

In [16]:
#cell1
import pandas as pd
pd.set_option("display.max_columns", None)

In [17]:
df = pd.DataFrame(
    [
        ["SUS", "J69P", "コイル", 12000, 3],
        ["SUS", "J69P", "Buck-IC", 10000, 1],
        ["WSE", "310D", "コイル", 15000, 2],
        ["WSE", "310D", "NTF", 14000, 0],
        ["GSE", "J69P", "コイル", 9000, 4],
        ["GSE", "J69P", "Buck-IC", 8000, 2],
        ["MELMB", "310D", "コイル", 20000, 5],
        ["MELMB", "310D", "NTF", 18000, 1],
    ],
    columns=[
        "site",
        "model",
        "defect_category",
        "inspection_qty",
        "defect_qty",
    ],
)

df

    site model defect_category  inspection_qty  defect_qty
0    SUS  J69P             コイル           12000           3
1    SUS  J69P         Buck-IC           10000           1
2    WSE  310D             コイル           15000           2
3    WSE  310D             NTF           14000           0
4    GSE  J69P             コイル            9000           4
5    GSE  J69P         Buck-IC            8000           2
6  MELMB  310D             コイル           20000           5
7  MELMB  310D             NTF           18000           1

In [18]:
df_work = df.copy()
df_work

    site model defect_category  inspection_qty  defect_qty
0    SUS  J69P             コイル           12000           3
1    SUS  J69P         Buck-IC           10000           1
2    WSE  310D             コイル           15000           2
3    WSE  310D             NTF           14000           0
4    GSE  J69P             コイル            9000           4
5    GSE  J69P         Buck-IC            8000           2
6  MELMB  310D             コイル           20000           5
7  MELMB  310D             NTF           18000           1

In [19]:
df_work["site_total_defect_qty"] = (
    df_work.groupby("site")["defect_qty"].transform("sum")
)
df_work

,site,model,defect_category,inspection_qty,defect_qty,site_total_defect_qty
0,SUS,J69P,コイル,12000,3,4
1,SUS,J69P,Buck-IC,10000,1,4
2,WSE,310D,コイル,15000,2,2
3,WSE,310D,NTF,14000,0,2
4,GSE,J69P,コイル,9000,4,6
5,GSE,J69P,Buck-IC,8000,2,6
6,MELMB,310D,コイル,20000,5,6
7,MELMB,310D,NTF,18000,1,6

In [20]:
#cell5
df_work["site_total_inspection_qty"] = (
    df_work.groupby("site")["inspection_qty"].transform("sum")
)
df_work

,site,model,defect_category,inspection_qty,defect_qty,site_total_defect_qty,site_total_inspection_qty
0,SUS,J69P,コイル,12000,3,4,22000
1,SUS,J69P,Buck-IC,10000,1,4,22000
2,WSE,310D,コイル,15000,2,2,29000
3,WSE,310D,NTF,14000,0,2,29000
4,GSE,J69P,コイル,9000,4,6,17000
5,GSE,J69P,Buck-IC,8000,2,6,17000
6,MELMB,310D,コイル,20000,5,6,38000
7,MELMB,310D,NTF,18000,1,6,38000

In [23]:
df_work["site_defect_rate"] = (
    df_work["site_total_defect_qty"]
    / df_work["site_total_inspection_qty"]
)
df_work

,site,model,defect_category,inspection_qty,defect_qty,site_total_defect_qty,site_total_inspection_qty,site_defect_rate
0,SUS,J69P,コイル,12000,3,4,22000,0.000182
1,SUS,J69P,Buck-IC,10000,1,4,22000,0.000182
2,WSE,310D,コイル,15000,2,2,29000,0.000069
3,WSE,310D,NTF,14000,0,2,29000,0.000069
4,GSE,J69P,コイル,9000,4,6,17000,0.000353
5,GSE,J69P,Buck-IC,8000,2,6,17000,0.000353
6,MELMB,310D,コイル,20000,5,6,38000,0.000158
7,MELMB,310D,NTF,18000,1,6,38000,0.000158

In [24]:
#cell7

df_work["site_defect_ppm"] = (
    df_work["site_defect_rate"]
    * 1000000
)
df_work

,site,model,defect_category,inspection_qty,defect_qty,site_total_defect_qty,site_total_inspection_qty,site_defect_rate,site_defect_ppm
0,SUS,J69P,コイル,12000,3,4,22000,0.000182,181.818182
1,SUS,J69P,Buck-IC,10000,1,4,22000,0.000182,181.818182
2,WSE,310D,コイル,15000,2,2,29000,0.000069,68.965517
3,WSE,310D,NTF,14000,0,2,29000,0.000069,68.965517
4,GSE,J69P,コイル,9000,4,6,17000,0.000353,352.941176
5,GSE,J69P,Buck-IC,8000,2,6,17000,0.000353,352.941176
6,MELMB,310D,コイル,20000,5,6,38000,0.000158,157.894737
7,MELMB,310D,NTF,18000,1,6,38000,0.000158,157.894737

In [ ]:
df_site_check = df_work[
    [
        "site",
        "site_total_defect_qty",
        "site_total_inspection_qty",
        "site_defect_rate",
        "site_defect_ppm",
    ]
].drop_duplicates()

df_site_check = df_site_check.sort_values(
    "site"
).reset_index(
    drop=True
)
df_site_check

,site,site_total_defect_qty,site_total_inspection_qty,site_defect_rate,site_defect_ppm
0,GSE,6,17000,0.000353,352.941176
1,MELMB,6,38000,0.000158,157.894737
2,SUS,4,22000,0.000182,181.818182
3,WSE,2,29000,0.000069,68.965517