###### 131_2_extract_product_version_answer.ipynb

In [1]:
import pandas as pd
import re

In [2]:
df = pd.read_csv("dataset/review.csv", index_col="user_id")
df

         rating                                           comment
user_id
U101          5  Py-220を購入。他社と比べると1000円ほど高いですが、その分値段に見合う品質だと思います。
U102          3                2月の寒い時期に買ったけど3か月で壊れた（使用頻度は1日5回くらい）
U103          3          前回PY-110を買って、リピでPY-210を買いました。タイマー機能が便利です
U104          4   Pyシリーズはずっと使ってるのですが、使わない時に折りたためるのが○ですね。あとヘビが可愛い。
U105          5          カラーが選べるので220にしました。目立ちすぎず部屋に馴染むので気に入っています

In [4]:
selected_df = df["comment"].str.extractall(
    r"(PY-\d{3})",
    flags=re.IGNORECASE,
)
selected_df

                    0
user_id match
U101    0      Py-220
U103    0      PY-110
        1      PY-210