###### 130_2_student_subject_list_join_answer

In [14]:
import pandas as pd

pd.set_option("display.max_columns", None)

In [15]:
df_class = pd.DataFrame(
    [
        ["Alice", "1-A"],
        ["Bob", "1-B"],
    ],
    columns=["Name", "Class"],
)
df_class

    Name Class
0  Alice   1-A
1    Bob   1-B

In [16]:
df = pd.DataFrame(
    [
        ["Alice", "国語", 87],
        ["Alice", "数学", 72],
        ["Bob", "国語", 65],
        ["Bob", "理科", 92],
    ],
    columns=[
        "Name",
        "Subject",
        "Point",
    ],
)
df

    Name Subject  Point
0  Alice      国語     87
1  Alice      数学     72
2    Bob      国語     65
3    Bob      理科     92

In [17]:
sr = df.groupby("Name").Subject.apply("/".join)
sr

Name
Alice    国語/数学
Bob      国語/理科
Name: Subject, dtype: object

In [19]:
df_result = df_class.join(
    sr,
    "Name",
)

df_result

    Name Class Subject
0  Alice   1-A   国語/数学
1    Bob   1-B   国語/理科