###### 128_5_cross_tabulation

In [1]:
import numpy as np
import pandas as pd

In [2]:
rnd = np.random.default_rng(2)

In [5]:
data1 = rnd.choice(
    [
        "1-A",
        "1-B",
    ],
    60,
)
data1

array(['1-B', '1-A', '1-A', '1-B', '1-B', '1-B', '1-A', '1-B', '1-B',
       '1-B', '1-A', '1-A', '1-B', '1-B', '1-B', '1-B', '1-A', '1-B',
       '1-A', '1-A', '1-A', '1-B', '1-A', '1-B', '1-A', '1-B', '1-A',
       '1-A', '1-A', '1-B', '1-B', '1-A', '1-B', '1-B', '1-A', '1-A',
       '1-A', '1-A', '1-B', '1-A', '1-B', '1-B', '1-B', '1-A', '1-A',
       '1-B', '1-A', '1-B', '1-A', '1-A', '1-B', '1-B', '1-B', '1-B',
       '1-A', '1-B', '1-B', '1-A', '1-A', '1-A'], dtype='<U3')

In [6]:
data2 = rnd.choice(
    [
        "Science",
        "Social",
        "Sport",
    ],
    60,
)
data2

array(['Sport', 'Science', 'Social', 'Science', 'Sport', 'Social',
       'Science', 'Science', 'Science', 'Science', 'Sport', 'Sport',
       'Social', 'Science', 'Science', 'Social', 'Social', 'Social',
       'Social', 'Social', 'Social', 'Social', 'Social', 'Sport', 'Sport',
       'Sport', 'Science', 'Social', 'Sport', 'Social', 'Science',
       'Social', 'Social', 'Sport', 'Social', 'Science', 'Science',
       'Sport', 'Sport', 'Social', 'Science', 'Science', 'Sport',
       'Science', 'Social', 'Sport', 'Science', 'Sport', 'Science',
       'Science', 'Science', 'Science', 'Social', 'Science', 'Social',
       'Sport', 'Social', 'Science', 'Sport', 'Science'], dtype='<U7')

In [8]:
df = pd.DataFrame(
    {
        "class": data1,
        "club": data2,
    }
)
df.head()

  class     club
0   1-B    Sport
1   1-A  Science
2   1-A   Social
3   1-B  Science
4   1-B    Sport

In [11]:
dfc = df.reset_index()
dfc.head()

   index class     club
0      0   1-B    Sport
1      1   1-A  Science
2      2   1-A   Social
3      3   1-B  Science
4      4   1-B    Sport

In [16]:
df_result = dfc.pivot_table(
    values="index",
    columns="club",
    index="class",
    aggfunc="count",
)
df_result

club   Science  Social  Sport
class
1-A         11      12      6
1-B         12       9     10