###### 130_3_practical_defect_category_site_dict.ipynb

In [1]:
#cell 1
import pandas as pd
pd.set_option("display.max_columns", None)

In [3]:
#cell2 
df_defect = pd.DataFrame(
    [
        ["SUS", "J69P", "コイル", 3],
        ["SUS", "J69P", "Buck-IC", 1],
        ["SUS", "J69P", "コイル", 2],
        ["SUS", "310D", "NTF", 1],
        ["WSE", "310D", "コイル", 2],
        ["WSE", "310D", "NTF", 0],
        ["GSE", "J69P", "コイル", 4],
        ["GSE", "J69P", "Buck-IC", 2],
        ["MELMB", "310D", "コイル", 5],
        ["MELMB", "310D", "NTF", 1],
    ],
    columns=[
        "site",
        "model",
        "defect_category",
        "defect_qty",
    ],
)
df_defect

    site model defect_category  defect_qty
0    SUS  J69P             コイル           3
1    SUS  J69P         Buck-IC           1
2    SUS  J69P             コイル           2
3    SUS  310D             NTF           1
4    WSE  310D             コイル           2
5    WSE  310D             NTF           0
6    GSE  J69P             コイル           4
7    GSE  J69P         Buck-IC           2
8  MELMB  310D             コイル           5
9  MELMB  310D             NTF           1

In [4]:
#cell3 

df_work = df_defect[
    [
        "defect_category",
        "site",
        "defect_qty",
    ]
].copy()

df_work

  defect_category   site  defect_qty
0             コイル    SUS           3
1         Buck-IC    SUS           1
2             コイル    SUS           2
3             NTF    SUS           1
4             コイル    WSE           2
5             NTF    WSE           0
6             コイル    GSE           4
7         Buck-IC    GSE           2
8             コイル  MELMB           5
9             NTF  MELMB           1

In [6]:
#cell4
df_work_positive = df_work[
    df_work["defect_qty"] > 0
].copy()

df_work_positive

  defect_category   site  defect_qty
0             コイル    SUS           3
1         Buck-IC    SUS           1
2             コイル    SUS           2
3             NTF    SUS           1
4             コイル    WSE           2
6             コイル    GSE           4
7         Buck-IC    GSE           2
8             コイル  MELMB           5
9             NTF  MELMB           1

In [7]:
#cell5
df_unique = df_work_positive.drop_duplicates(
    [
        "defect_category",
        "site",
    ]
)
df_unique

  defect_category   site  defect_qty
0             コイル    SUS           3
1         Buck-IC    SUS           1
3             NTF    SUS           1
4             コイル    WSE           2
6             コイル    GSE           4
7         Buck-IC    GSE           2
8             コイル  MELMB           5
9             NTF  MELMB           1

In [9]:
#cell6
sr_category_site = (
    df_unique.groupby("defect_category")["site"].apply(list)
)
sr_category_site

defect_category
Buck-IC                [SUS, GSE]
NTF                  [SUS, MELMB]
コイル        [SUS, WSE, GSE, MELMB]
Name: site, dtype: object

In [10]:
#cell7
dict_category_site = sr_category_site.to_dict()
dict_category_site

{'Buck-IC': ['SUS', 'GSE'],
 'NTF': ['SUS', 'MELMB'],
 'コイル': ['SUS', 'WSE', 'GSE', 'MELMB']}

In [11]:
dict_category_site["コイル"]

['SUS', 'WSE', 'GSE', 'MELMB']