###### 128_7_split_string_column_to_rows

In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame(
    {
        "国": [
            "日本",
            "フランス",
        ],
        "都市": [
            "東京/大阪",
            "パリ",
        ],
    }
)
df

      国     都市
0    日本  東京/大阪
1  フランス     パリ

In [5]:
df = df.set_index("国").都市.str.extractall(r"(?P<都市>[^/]+)")
df = df.reset_index("国").reset_index(drop=True)

In [6]:
df

      国  都市
0    日本  東京
1    日本  大阪
2  フランス  パリ