###### 128_6_split_string_column

In [6]:
import pandas as pd

In [7]:
df = pd.DataFrame(
    {
        "国": ["日本", "フランス"],
        "都市": ["東京/大阪", "パリ"],
    }
)
df

      国     都市
0    日本  東京/大阪
1  フランス     パリ

In [12]:
df[["都市1", "都市2"]] = df["都市"].str.extract(r"(\w+)/(\w*)")
df

      国     都市  都市1  都市2
0    日本  東京/大阪   東京   大阪
1  フランス     パリ  NaN  NaN

In [13]:
df.drop("都市", axis=1, inplace=True)
df

      国  都市1  都市2
0    日本   東京   大阪
1  フランス  NaN  NaN